/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Implementaciones;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author stink
 */
public class Estadisticas extends javax.swing.JFrame {
    Datos dt = new Datos();
    private static int cantTotal=0;
    private static int obsTotal=0;
    /**
     * Creates new form Estadisticas
     */
    public Estadisticas() {
        initComponents();
        Image icon = new ImageIcon(getClass().getResource("/Imagen/Icono2E.png")).getImage();        
        setIconImage(icon);
        this.setLocationRelativeTo(null);
        int aux[][]=dt.cant;
        cantTotal=dt.sumaE(aux);
        int aux2[]=dt.cantObs;
        obsTotal=dt.sumaE(aux2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        op = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        report = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3), "Reportes", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Rockwell Extra Bold", 1, 24), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Segun :");

        op.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 14)); // NOI18N
        op.setForeground(new java.awt.Color(255, 255, 255));
        op.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--------------", "Cantidad por modelo", "Cantidad de obsequios", "Ventas por modelos", "Reporte General", " ", " " }));
        op.setOpaque(false);
        op.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opActionPerformed(evt);
            }
        });

        report.setEditable(false);
        report.setColumns(20);
        report.setRows(5);
        report.setTabSize(7);
        report.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        jScrollPane1.setViewportView(report);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/regresar80.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 0, 0));
        jLabel16.setText("SALIR");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/escoba80.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Limpiar");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/archivar80.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Archivar");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/historial80.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Historial");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(op, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(64, 64, 64)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel16))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addGap(14, 14, 14))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(op, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addComponent(jLabel7))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addContainerGap(85, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addGap(5, 5, 5))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 740, 430));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/reporte800.jpg"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opActionPerformed
        //Lee opcion
        int tip=this.op.getSelectedIndex();
        //Reporte segun
        switch (tip) {
            case 1://Cantidad modelo
                //Limpieza de area de reporte
                this.report.setText("");
                
                //Titulos
                this.report.append("REPORTE CANTIDAD POR MODELO\n");
                this.report.append("--------------------"
                        + "-----------------------------"
                        + "-----------------------------\n");
                this.report.append("Cod.\tMod\tStock\tVendidos\n");
                this.report.append("--------------------"
                        + "-----------------------------"
                        + "-----------------------------\n\n");
                //Impresion de reporte
                for (int i = 1; i < dt.cant.length; i++) {
                    this.report.append(dt.dG[i][0]
                                    +"\t"+dt.dG[i][1]
                                    +"\t"+dt.cant[i][0]
                                    +"\t"+dt.cant[i][1]+"\n"); 
                }                
                //Total de cantidad
                this.report.append("--------------------"
                        + "-----------------------------"
                        + "-----------------------------\n");
                this.report.append("\t\tTotal\t"+cantTotal+"\n\n");
                //Imprimir barra de asteriscos
                this.report.append("--------------------"
                        + "-----------------------------"
                        + "-----------------------------\n");
                this.report.append("Cod.\tMod\tCantidad\n");
                this.report.append("--------------------"
                        + "-----------------------------"
                        + "-----------------------------\n\n");
                for (int i = 1; i < dt.cant.length; i++) {
                    this.report.append(dt.dG[i][0]
                                    +"\t"+dt.dG[i][1]
                                    +"\t"+dt.cant[i][1]
                                    +"\t"+dt.asteriscos(dt.cant[i][1])+"\n");  
                }
                break;
            case 2://Cantidad de obsequios
                //Limpieza de area de reporte
                this.report.setText("");                
                //Titulos
                this.report.append("REPORTE OBSEQUIOS\n");
                this.report.append("--------------------"
                        + "-----------------------------"
                        + "-----------------------------\n");
                this.report.append("N°\tObsq.\tEntregado\n");
                this.report.append("--------------------"
                        + "-----------------------------"
                        + "-----------------------------\n");
                //Impresion de reporte
                for (int i = 1; i < dt.obs.length; i++) {
                    this.report.append(i
                            +"\t"+dt.obs[i]
                            +"\t"+dt.cantObs[i]+"\n");
                }
                //Total de obsequios
                this.report.append("--------------------"
                        + "-----------------------------"
                        + "-----------------------------\n");
                this.report.append("\n\tTotal\t"+obsTotal);                
                break;
            case 3://Ventas por modelo       
                //Limpieza de area de reporte
                this.report.setText("");
                //Titulos
                this.report.append("REPORTE POR MODELOS\n");
                this.report.append("--------------------"
                        + "-----------------------------"
                        + "-----------------------------\n");
                this.report.append("Cod.\tMod\tVentas\n");
                this.report.append("--------------------"
                        + "-----------------------------"
                        + "-----------------------------\n");
                //Imprimir reporte
                for (int i = 1; i < dt.venta.length; i++) {
                    this.report.append(dt.dG[i][0]
                                    +"\t"+dt.dG[i][1]
                                    +"\t"+dt.venta[i]+"\n");
                }
                //Tota deventas
                this.report.append("--------------------"
                        + "-----------------------------"
                        + "-----------------------------\n");
                this.report.append("\n\tTotal\t"+dt.monto);
                break;
            case 4://Reporte General
                //Limpieza de area de reporte
                this.report.setText("");
                //Imprimir reporte
                this.report.append("REPORTE GENERAL\n");
                this.report.append("--------------------"
                        + "-----------------------------"
                        + "-----------------------------\n");
                this.report.append("N° de ventas :\t\t"+dt.ventas+"\n");
                this.report.append("Motos vendidas :\t"+cantTotal+"\n");
                this.report.append("Obsequios dados :\t"+obsTotal+"\n");
                this.report.append("Total de ingresos :\t"+dt.monto+"\n");
                break;
            default:                
                //Limpieza de area de reporte
                this.report.setText("");
                
        }
    }//GEN-LAST:event_opActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        Menu me = new Menu();
        this.dispose();
        me.setVisible(true);

    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        this.op.setSelectedIndex(0);
        this.report.setText("");        
    }//GEN-LAST:event_jLabel3MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        if (dt.ventas==0) {
            v_Info vI = new v_Info();
            vI.titulo="Información";
            vI.info1="Aun no se ";
            vI.info2="han generado";
            vI.info3="Ventas";            
            vI.setVisible(true);
        }
    }//GEN-LAST:event_formWindowOpened

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        String mensaje=this.report.getText();
        dt.Reporte(mensaje);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        //Limpieza de elementos
        this.op.setSelectedIndex(0);
        this.report.setText("");
        //Muestra de historial
        this.report.append(dt.Historial());
    }//GEN-LAST:event_jLabel7MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Estadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Estadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Estadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Estadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Estadisticas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> op;
    private javax.swing.JTextArea report;
    // End of variables declaration//GEN-END:variables
}
