/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Implementaciones;

import java.awt.Image;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;

/**
 *
 * @author stink
 */
public class v_Info extends javax.swing.JFrame {
    public static String titulo;
    public static String info1;
    public static String info2;
    public static String info3;
    /**
     * Creates new form v_Info
     */
    public v_Info() {
        initComponents();
        Image icon = new ImageIcon(getClass().getResource("/Imagen/Icono2E.png")).getImage();        
        setIconImage(icon);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtitulo = new javax.swing.JLabel();
        jinf1 = new javax.swing.JLabel();
        jinfo2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jinfo3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtitulo.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 18)); // NOI18N
        jtitulo.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(jtitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 300, 30));

        jinf1.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 18)); // NOI18N
        jinf1.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(jinf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 300, 40));

        jinfo2.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 18)); // NOI18N
        jinfo2.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(jinfo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 300, 40));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(115, 6, 19));
        jButton1.setText("OK");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(115, 6, 19)));
        jButton1.setBorderPainted(false);
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jButton1KeyReleased(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, -1, -1));

        jinfo3.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 18)); // NOI18N
        jinfo3.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(jinfo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 300, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/informacion400.jpg"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0), 2));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 250));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.jtitulo.setText(titulo);
        this.jinf1.setText(info1);
        this.jinfo2.setText(info2);
        this.jinfo3.setText(info3);
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            this.dispose();
        }
    }//GEN-LAST:event_jButton1KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(v_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(v_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(v_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(v_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new v_Info().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jinf1;
    private javax.swing.JLabel jinfo2;
    private javax.swing.JLabel jinfo3;
    private javax.swing.JLabel jtitulo;
    // End of variables declaration//GEN-END:variables
}
