/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Implementaciones;
import java.awt.Image;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
/**
 *
 * @author stink
 */
public class Ventas extends javax.swing.JFrame {
    //Creacion de objetos
    Datos dt = new Datos();    
    private static double top;
    public static int consulta;
    /**
     * Creates new form Ventas
     */
    public Ventas() {
        initComponents();
        Image icon = new ImageIcon(getClass().getResource("/Imagen/Icono2E.png")).getImage();        
        setIconImage(icon);
        this.setLocationRelativeTo(this);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        combCod = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jmod = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jcil = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jaño = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jpre = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jcan = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        combPag = new javax.swing.JComboBox<>();
        bvent = new javax.swing.JLabel();
        bcancel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jdisp = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Boleta = new javax.swing.JTextArea();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jtotal = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 542));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(800, 542));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Rockwell Extra Bold", 3, 56)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("VENTAS");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 290, 20));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2), "Pedido", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Rockwell Extra Bold", 3, 24), new java.awt.Color(0, 255, 102))); // NOI18N
        jPanel1.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Codigo :");

        combCod.setBackground(new java.awt.Color(102, 102, 102));
        combCod.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 12)); // NOI18N
        combCod.setForeground(new java.awt.Color(255, 255, 255));
        combCod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--------", "CD 00", "CD 01", "CD 02", "CD 03", "CD 04" }));
        combCod.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        combCod.setMinimumSize(new java.awt.Dimension(110, 21));
        combCod.setPreferredSize(new java.awt.Dimension(110, 21));
        combCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combCodActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Modelo :");

        jmod.setEditable(false);
        jmod.setBackground(new java.awt.Color(26, 26, 28));
        jmod.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 12)); // NOI18N
        jmod.setForeground(new java.awt.Color(255, 255, 255));
        jmod.setMaximumSize(new java.awt.Dimension(110, 21));
        jmod.setMinimumSize(new java.awt.Dimension(110, 21));
        jmod.setPreferredSize(new java.awt.Dimension(110, 21));

        jLabel5.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Cilindrada : ");

        jcil.setEditable(false);
        jcil.setBackground(new java.awt.Color(26, 26, 28));
        jcil.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 12)); // NOI18N
        jcil.setForeground(new java.awt.Color(255, 255, 255));
        jcil.setMaximumSize(new java.awt.Dimension(110, 21));
        jcil.setMinimumSize(new java.awt.Dimension(110, 21));
        jcil.setPreferredSize(new java.awt.Dimension(110, 21));

        jLabel6.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Año : ");

        jaño.setEditable(false);
        jaño.setBackground(new java.awt.Color(26, 26, 28));
        jaño.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 12)); // NOI18N
        jaño.setForeground(new java.awt.Color(255, 255, 255));
        jaño.setMaximumSize(new java.awt.Dimension(110, 21));
        jaño.setMinimumSize(new java.awt.Dimension(110, 21));
        jaño.setPreferredSize(new java.awt.Dimension(110, 21));

        jLabel7.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Precio : ");

        jpre.setEditable(false);
        jpre.setBackground(new java.awt.Color(26, 26, 28));
        jpre.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 12)); // NOI18N
        jpre.setForeground(new java.awt.Color(255, 255, 255));
        jpre.setMaximumSize(new java.awt.Dimension(110, 21));
        jpre.setMinimumSize(new java.awt.Dimension(110, 21));
        jpre.setPreferredSize(new java.awt.Dimension(110, 21));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel8.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Cantidad : ");

        jcan.setBackground(new java.awt.Color(26, 26, 28));
        jcan.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 12)); // NOI18N
        jcan.setForeground(new java.awt.Color(255, 255, 255));
        jcan.setMaximumSize(new java.awt.Dimension(110, 21));
        jcan.setMinimumSize(new java.awt.Dimension(110, 21));
        jcan.setPreferredSize(new java.awt.Dimension(110, 21));

        jLabel14.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Pago : ");

        combPag.setBackground(new java.awt.Color(102, 102, 102));
        combPag.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 12)); // NOI18N
        combPag.setForeground(new java.awt.Color(255, 255, 255));
        combPag.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "----------", "Contado", "Tarjeta" }));
        combPag.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        combPag.setMaximumSize(new java.awt.Dimension(110, 21));
        combPag.setMinimumSize(new java.awt.Dimension(110, 21));
        combPag.setPreferredSize(new java.awt.Dimension(110, 21));
        combPag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combPagActionPerformed(evt);
            }
        });

        bvent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/VentaCargaE.png"))); // NOI18N
        bvent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bventMouseClicked(evt);
            }
        });

        bcancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Cancelar50.png"))); // NOI18N
        bcancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bcancelMouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 255, 0));
        jLabel9.setText("Vender");

        jLabel18.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 0, 51));
        jLabel18.setText("Cancelar");

        jLabel24.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Disponibles:");

        jdisp.setEditable(false);
        jdisp.setBackground(new java.awt.Color(26, 26, 28));
        jdisp.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 12)); // NOI18N
        jdisp.setForeground(new java.awt.Color(255, 255, 255));
        jdisp.setMaximumSize(new java.awt.Dimension(110, 21));
        jdisp.setMinimumSize(new java.awt.Dimension(110, 21));
        jdisp.setPreferredSize(new java.awt.Dimension(110, 21));

        jLabel25.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("(0 ~ 20)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jaño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jmod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel8)
                    .addComponent(jLabel24))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bcancel)
                        .addGap(32, 32, 32))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jcan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combPag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jdisp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(bvent)
                                .addComponent(jLabel9)))
                        .addGap(19, 19, 19))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(combCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel14)
                                        .addComponent(combPag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jmod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(jcil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(11, 11, 11)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jaño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(jpre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel24)
                                    .addComponent(jdisp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(42, 42, 42)
                                .addComponent(jLabel25)
                                .addGap(35, 35, 35))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bvent)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(jLabel8)
                            .addComponent(jcan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bcancel)))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 740, 210));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2), "Venta", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Rockwell Extra Bold", 3, 24), new java.awt.Color(0, 255, 102))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setOpaque(false);

        jLabel11.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 102, 0));
        jLabel11.setText("Imp");

        jLabel12.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 102, 0));
        jLabel12.setText("Dsc. Mnt");

        Boleta.setEditable(false);
        Boleta.setColumns(20);
        Boleta.setRows(5);
        Boleta.setTabSize(7);
        jScrollPane1.setViewportView(Boleta);

        jLabel19.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 102, 0));
        jLabel19.setText("SubTotal");

        jLabel20.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 102, 0));
        jLabel20.setText("Dsc. Cant");

        jLabel21.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 102, 0));
        jLabel21.setText("Dsc. Pag");

        jLabel22.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 102, 0));
        jLabel22.setText("Cant");

        jLabel15.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 102, 0));
        jLabel15.setText("IGV ");

        jLabel10.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("Total :");

        jtotal.setEditable(false);
        jtotal.setBackground(new java.awt.Color(26, 26, 28));
        jtotal.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 12)); // NOI18N
        jtotal.setForeground(new java.awt.Color(255, 255, 255));
        jtotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtotal.setMaximumSize(new java.awt.Dimension(110, 21));
        jtotal.setMinimumSize(new java.awt.Dimension(110, 21));
        jtotal.setPreferredSize(new java.awt.Dimension(110, 21));

        jLabel23.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 102, 0));
        jLabel23.setText("Obsequio");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(jtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addComponent(jLabel23)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel20)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel21)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel15)
                        .addGap(23, 23, 23)
                        .addComponent(jLabel19)
                        .addGap(100, 100, 100)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel23)
                    .addComponent(jLabel21)
                    .addComponent(jLabel15)
                    .addComponent(jLabel20)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 740, 220));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/regresar80.png"))); // NOI18N
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });
        jLabel17.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jLabel17KeyReleased(evt);
            }
        });
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, -1, -1));

        jLabel16.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 0, 0));
        jLabel16.setText("SALIR");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 30, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/VentasE.jpg"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jLabel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jLabel1KeyReleased(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        Menu me = new Menu();
        // Cierre de la ventana Ventas
        this.dispose();
        //Retorno a la ventana Menu
        me.setVisible(true);
    }//GEN-LAST:event_jLabel17MouseClicked

    private void combCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combCodActionPerformed
        // Carga los datos generales de la moto en venta
        int cod = combCod.getSelectedIndex();
        this.jmod.setText(dt.dG[cod][1]);
        this.jcil.setText(dt.dG[cod][2]);
        this.jaño.setText(dt.dG[cod][3]);
        this.jpre.setText(dt.dG[cod][4]);
        if (cod==0) {
            this.jdisp.setText("");
        }else{
            this.jdisp.setText(""+dt.cant[cod][0]);
        }        
    }//GEN-LAST:event_combCodActionPerformed

    private void combPagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combPagActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combPagActionPerformed

    private void bcancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bcancelMouseClicked
        /* Limpia todos los campos y los vuelve a su estado inicial
           Sin contar el area de texto*/
        this.combCod.setSelectedIndex(0);
        this.jmod.setText("");
        this.jcil.setText("");
        this.jaño.setText("");
        this.jpre.setText("");
        this.combPag.setSelectedIndex(0);
        this.jcan.setText("");
        top=0;
        this.jtotal.setText("");
        this.Boleta.setText("");  
    }//GEN-LAST:event_bcancelMouseClicked

    private void bventMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bventMouseClicked
        // TODO add your handling code here:
        try {
            //Lectura de codigo
            int cod=this.combCod.getSelectedIndex();
            //Lectura de medio de pago
            int pag=this.combPag.getSelectedIndex();
            //Lectuar de cantidad
            int cant=Integer.parseInt(this.jcan.getText());
            //Si no se escogio codigo
            if (cod==0) {
                v_Error vE = new v_Error();
                vE.tmsj="Seleccionar";
                vE.tmsj2="un codigo!!";
                vE.setVisible(true);
            }else{
                //Si no se selecciono medio de pago
                if (pag==0) {
                    v_Error vE = new v_Error();
                    vE.tmsj="Seleccionar medio";
                    vE.tmsj2="de pago!!";
                    vE.setVisible(true);
                }else{
                    //Si la cantidad excede el inventario
                    if (cant>dt.cant[cod][0]) {
                        v_Error vE = new v_Error();
                        vE.tmsj="Excedio el ";
                        vE.tmsj2="stock!!";
                        vE.setVisible(true);
                    }else{
                        //Si la cantidadd es negativa o mayor a 20
                        if (cant<0 || cant>20) {
                            v_Error vE = new v_Error();
                            vE.tmsj="Cantidad fuera ";
                            vE.tmsj2="de rango!!";
                            vE.setVisible(true);
                        }else{
                            //Disminucion de inventario
                            dt.cant[cod][0]-=cant;
                            this.jdisp.setText(""+dt.cant[cod][0]);
                            //Aumente de conteo
                            dt.cant[cod][1]+=cant;
                            //Leer precio
                            double pre=Double.parseDouble(this.jpre.getText());
                            //Calcular importe
                            double imp=pre*cant;
                            //Variable de obsequio
                            int opb=(int)
                                    (Math.random()*((dt.obs.length-1)-1+1)+1);
                            //Obsequio
                            String reg=dt.obs[opb];
                            //Contador de obsequios
                            dt.cantObs[opb]++;
                            //Descuento por monto                            
                            double des1;
                            if (imp>=(Double.parseDouble(dt.desc[0][0]))) {
                                des1=imp*Double.parseDouble(dt.desc[0][1]);
                                des1=dt.redondedo(des1);
                            }else{
                                des1=0;
                            }
                            //Descuento por cantdad
                            double des2;
                            if (cant>=(Integer.parseInt(dt.desc[1][0]))) {
                                des2=(imp-des1)
                                        *Double.parseDouble(dt.desc[1][1]);
                                des2=dt.redondedo(des2);
                            }else{
                                des2=0;
                            }
                            //Descuento por medio de pago
                            double des3;
                            switch (pag) {
                                case 1:
                                    des3=(imp-des1-des2)
                                        *Double.parseDouble(dt.desc[2][1]);
                                    des3=dt.redondedo(des3);
                                    break;
                                case 2:
                                    des3=(imp-des1-des2)
                                        *Double.parseDouble(dt.desc[3][1]);
                                    des3=dt.redondedo(des3);
                                    break;
                                default:
                                    des3=0;;
                            }                            
                            //Calcular el igv
                            double igv=imp*Double.parseDouble(dt.desc[4][0]);
                            igv=dt.redondedo(igv);
                            //Pago neto
                            double neto=imp-(des1+des2+des3)+igv;
                            //Carga venta por modelo
                            dt.venta[cod]+=neto;
                            //Aumento de venta
                            dt.ventas++;
                            top+=neto;
                            dt.monto+=neto;
                            //Salida de datos
                            this.Boleta.append(""+cant+
                                " \t"+reg+
                                " \t"+imp+
                                " \t- "+des1+
                                " \t- "+des2+
                                " \t- "+des3+
                                " \t+ "+igv+
                                " \tS/. "+neto+"\n");
                            this.jtotal.setText(""+top);
                        }
                    }
                }
            }
        } catch (NumberFormatException e) {
            //Error por formato de cantidad invalido
            v_Error vE = new v_Error();
            vE.tmsj="Cantidad invalida";
            vE.tmsj2="o no ingresada!!";
            vE.setVisible(true);
            this.jcan.setText("");
        }
    }//GEN-LAST:event_bventMouseClicked

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
        // TODO add your handling code here:
       
    }//GEN-LAST:event_formKeyReleased

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        combCod.setSelectedIndex(consulta);
    }//GEN-LAST:event_formWindowActivated

    private void jLabel1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel1KeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jLabel1KeyReleased

    private void jLabel17KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel17KeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jLabel17KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Boleta;
    private javax.swing.JLabel bcancel;
    private javax.swing.JLabel bvent;
    private javax.swing.JComboBox<String> combCod;
    private javax.swing.JComboBox<String> combPag;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jaño;
    private javax.swing.JTextField jcan;
    private javax.swing.JTextField jcil;
    private javax.swing.JTextField jdisp;
    private javax.swing.JTextField jmod;
    private javax.swing.JTextField jpre;
    private javax.swing.JTextField jtotal;
    // End of variables declaration//GEN-END:variables
}
